const pseudoClass = [
    "active",
    "checked",
    "disabled",
    "empty",
    "enabled",
    "first-child",
    "first-of-type",
    "focus",
    "hover",
    "in-range",
    "invalid",
    "lang",
    "last-child",
    "last-of-type",
    "link",
    "not",
    "nth-child",
    "nth-last-child",
    "nth-last-of-type",
    "nth-of-type",
    "only-of-type",
    "only-child",
    "optional",
    "out-of-range",
    "read-only",
    "read-write",
    "required",
    "root",
    "target",
    "valid",
    "visited",
    "after",
    "before",
    "first-letter",
    "first-line",
    "selection",
    //#region 模板
    //  ":active",
    //  ":checked",
    //  ":disabled",
    //  ":empty",
    //  ":enabled",
    //  ":first-child",
    //  ":first-of-type",
    //  ":focus",
    //  ":hover",
    //  ":in-range",
    //  ":invalid",
    //  ":lang(language)",
    //  ":last-child",
    //  ":last-of-type",
    //  ":link",
    //  ":not(selector)",
    //  ":nth-child(n)",
    //  ":nth-last-child(n)",
    //  ":nth-last-of-type(n)",
    //  ":nth-of-type(n)",
    //  ":only-of-type",
    //  ":only-child",
    //  ":optional",
    //  ":out-of-range",
    //  ":read-only",
    //  ":read-write",
    //  ":required",
    //  ":root",
    //  ":target",
    //  ":valid",
    //  ":visited",
    //  ":after",
    //  ":before",
    //  ":first-letter",
    //  ":first-line",
    //  ":selection",
    //#endregion
]

export {
    pseudoClass
}